modLoader="javafml"
loaderVersion="${forge_loader_version_range}"
license="${mod_license}"
issueTrackerURL="${mod_issue_tracker_url}"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="${mod_update_json_url}"
displayURL="${mod_homepage_url}"
logoFile="${mod_id}.png"
credits="${mod_credits}"
authors="${mod_authors}"
description="${mod_description}"
# Disable Sodium/Rubidium's chunk rendering optimisations because they break our chunk rendering
[mods."sodium:options"]
"features.chunk_rendering"=false

[[dependencies.nocubes]]
modId="forge"
mandatory=true
versionRange="[40,)"
ordering="NONE"
side="BOTH"

[[dependencies.nocubes]]
modId="minecraft"
mandatory=true
versionRange="[1.20,)"
ordering="NONE"
side="BOTH"
