modLoader="javafml"
loaderVersion="${forge_loader_version_range}"
license="${license}"
issueTrackerURL="${issue_tracker_url}"
[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
updateJSONURL="${update_json_url}"
displayURL="${project_homepage_url}"
logoFile="${mod_id}.png"
credits="${mod_credits}"
authors="${mod_authors}"
description='''${mod_description}'''
# Disable Sodium/Rubidium's chunk rendering optimisations because they break our chunk rendering
[mods."sodium:options"]
"features.chunk_rendering"=false

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
